# Generated by Django 4.1.3 on 2023-11-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Health', 'Health'), ('Subscriptions', 'Subscriptions'), ('Clothing', 'Clothing'), ('Travelling', 'Travelling'), ('Education', 'Education'), ('Others', 'Others')], help_text='Category of Expense', max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Crypto', 'Crypto'), ('Freelancing', 'Freelancing'), ('Investments', 'Investments'), ('Bank', 'Bank'), ('Others', 'Others')], help_text='Category of Income', max_length=20),
        ),
    ]
