# Generated by Django 4.1.3 on 2023-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_expense_name_expense_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
