# Generated by Django 4.1.3 on 2023-11-08 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expense_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='income',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='income',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
