# Generated by Django 4.1.3 on 2023-11-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_expense_type_income_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
    ]
